version: "3"

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306